package com.example.WebAppPayments.controller.command;

/**
 * Constants for command names
 */
public enum CommandName {

    LOGIN,
    LOGOUT,
    REGISTERNEWUSER,
    GETUSERS,
    BLOCKUSER,
    UNBLOCKUSER,

    CHOOSELOCALECOMMAND,

    GETCARDS,
    DELETECARD,
    EXTENDCARDVALIDDATE,

    GETACCOUNTS,
    DELETEACCOUNT,

    GETPAYMENTS,

    // other pages
    GOTOPROFILEPAGE,
    GOTOUSERSPAGE,
    GOTOACCOUNTPAGE,
    GOTOCARDSPAGE,
    GOTONEWPAYMENTPAGE,
    GOTOPAYMENTPAGE,
    GOTOCOMPLETEDPAYMENTPAGE,
    //

    GOTOMAINPAGE,
    GOTOREGISTERPAGE,
    GOTOLOGINPAGE,
    GOTOCONTACTSPAGE,
    GOTOABOUTPAGE,

    UPDATEUSERINFO,
    ADDNEWACCOUNT,
    ADDNEWCARD,
    ADDNEWPAYMENT,

    GETPROFILEINFO

}
